robot1:
  arm_id: "fr3"
  arm_prefix: ""
  fake_sensor_commands: "false" 
  # load_gripper=false: avoid concurrent gripper session tearing down arm FCI.
  joint_sources: ["joint_states"]
  joint_state_rate: 30
  load_gripper: "false" 
  namespace: ""
  robot_ip: "10.229.66.91" 
  urdf_file: "fr3/fr3.urdf.xacro" 
  use_fake_hardware: "false" 
  use_rviz: "false" 